# Site wide configuration

title:            Ícaro Bichir
locale:           en_US
url:              //icarobichir.com.br


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

#Google analytics
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-63079769-1'

# Site owner
owner:
  name: Ícaro Bichir
  avatar: bio-photo.jpg
  bio: "A geek that dreams to be a hacker became a programmer security especialist, and now, I'm a DevOps Analyst. ;)"
  disqus-shortname: icarobichir
  email: icbichir1@gmail.com
  github: icarobichir
  linkedin: icarobichir
  lastfm: icaro_0

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

